Added usb-serial adapter page under utilities

diff --git a/filesystem/ext2/files/usercode/mount-usb b/filesystem/ext2/files/usercode/mount-usb
--- a/filesystem/ext2/files/usercode/mount-usb
+++ b/filesystem/ext2/files/usercode/mount-usb
@@ -1,15 +1,47 @@
 #!/bin/sh
 
-mkdir -p /mnt/browser/usb >/dev/null 2>&1
-mount /dev/sda1 /mnt/browser/usb -t vfat >/dev/null 2>&1
-mount /dev/sdb1 /mnt/browser/usb -t vfat >/dev/null 2>&1
-mount /dev/sdc1 /mnt/browser/usb -t vfat >/dev/null 2>&1
-mount /dev/sdd1 /mnt/browser/usb -t vfat >/dev/null 2>&1
-rmdir /mnt/browser/usb >/dev/null 2>&1
+# get the device the internal usb drive is mounted on
+INTUSB=`ls -l /dev/disk/by-label/rfs_boot | awk '{print $11}'`
+INTUSB=${INTUSB#../../}
 
-if [ -e /mnt/browser/usb ]; then
-    exit 0
-else
-    exit 1
+# make sure there is an argument containing a mount path
+if [ $# -eq 0 ]; then
+	exit 1
 fi
 
+# the mount location is passed to the script from Qt
+USBFOLDER=$1
+
+# create a usb mount point not already taken
+#i=1
+#USBFOLDER=/mnt/browser/usb$i
+#while [ -e $USBFOLDER ]
+#do
+#    i=$(( i + 1 ))
+#   USBFOLDER=/mnt/browser/usb$i
+#done
+
+# loop through all the devices
+for dev in sda sdb sdc sdd;
+do
+    # ignore the internal usb device
+    if [ "${INTUSB}" = "${dev}1" ]; then
+	continue
+    fi
+    
+    # check if the device is already mounted?
+    if [ -z "`mount | grep $dev`" ]; then
+	# device not mounted yet make a mount location
+	mkdir -p $USBFOLDER >/dev/null 2>&1
+	# try mounting the device
+	mount /dev/${dev}1 $USBFOLDER -t vfat >/dev/null 2>&1
+	if [ -n "`mount | grep $dev`" ]; then
+	    # device mounted properly, exit
+	    exit 0
+	fi
+	# mount failed remove the directory
+	rmdir $USBFOLDER >/dev/null 2>&1
+    fi
+done
+
+exit 1
